challenge_id = "nopcoding"

challenge_name = "NOP Coding"

challenge_description = '''
TODO: create a description here for
the challenge that is really cool
and interesting
'''

challenge_spoilers = '''
TODO: explain the challenge
here for the commentators
so that they can talk about it
'''
